#!/bin/bash -x
kubectl delete deployment wordpress
kubectl delete deployment wordpress-mysql
kubectl delete persistentvolumeclaim wp-pv-claim
kubectl delete persistentvolumeclaim mysql-pv-claim
kubectl delete secret mysql-pass
kubectl delete persistentvolume local-pv-1
kubectl delete persistentvolume local-pv-2
kubectl delete service wordpress
kubectl delete service wordpress-mysql

