#!/bin/bash
n=200
# get the HTML, find the host line, remove markup
for i in `seq 1 $n`;
do
   curl -s http://127.0.0.1:31806/cgi-bin/hello.cgi | \
       grep host | \
       sed 's/^<h3> host: //' | sed 's/ <.*//'
done
